# Quickly check links in Markdown, HTML, and text files using lychee.
# https://github.com/lycheeverse/lychee-action
name: Check Links

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 1' # Mondays at 9am UTC

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.8.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          args: --verbose --no-progress './**/*.md' --accept 200,201,204,206,401,403,406,429,999 --exclude-path './Templates'

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue, good first issue
